import Head from "next/head";
import AboutScreen from "@/screens/about";

export default function About() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutScreen />
    </>
  );
}
