import Head from "next/head";
import VisionPrimeScreen from "@/screens/works/pages/vision-prime";

export default function VisionPrime() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/title.svg" />
      </Head>
      <VisionPrimeScreen />
    </>
  );
}
