import Head from "next/head";
import SportCollectionScreen from "@/screens/works/pages/sport-collection";

export default function SportCollection() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SportCollectionScreen />
    </>
  );
}
