import Head from "next/head";
import WorksBrandScreen from "@/screens/works/pages/branding";

export default function WorksBranding() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WorksBrandScreen />
    </>
  );
}
