import Head from "next/head";
import ServiceScreen from "@/screens/services";

export default function Services() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ServiceScreen />
    </>
  );
}
