import Head from "next/head";
import WorksWebScreen from "@/screens/works/pages/web";

export default function WorksWeb() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/title.svg" />
      </Head>
      <WorksWebScreen />
    </>
  );
}
