import PodiumAw23Screen from "@/screens/works/pages/podium-aw23";
import Head from "next/head";

export default function PodiumAw23() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PodiumAw23Screen />
    </>
  );
}
