import CoreAIScreen from "@/screens/works/pages/coreai";
import Head from "next/head";

export default function CoreAI() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/title.svg" />
      </Head>
      <CoreAIScreen />
    </>
  );
}
