import Head from "next/head";
import WorksAllScreen from "@/screens/works/pages/all";

export default function WorksAll() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/title.svg" />
      </Head>
      <WorksAllScreen />
    </>
  );
}
