import Head from "next/head";
import WorksUXUIScreen from "@/screens/works/pages/ux-ui";

export default function WorksUXUI() {
  return (
    <>
      <Head>
        <title>Zucko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WorksUXUIScreen />
    </>
  );
}
